Ext.define('App.model.partEngineering.ActStruct', {
	extend: 'App.model.common.Base',
	fields: [{
		name: 'id',
		mapping: function(data) {
			return Ext.id();
		}
	}, {
		name: 'partCode'
	}, {
		name: 'usageStatus'
	}, {
		name: 'deletedCode'
	}, {
		name: 'deletedName'
	}, {
		name: 'qty'
	}, {
		name: 'aftersalesPart'
	}, {
		name: 'isInheritanceStructure'
	}, {
		name: 'isInheritanceStructureName'
	}, {
		name: 'usageNote'
	}, {
		name: 'productUpcfnaCode'
	}, {
		name: 'parentPartCode'
	}, {
		name: 'parentPartNameZh'
	}, {
		name: 'parentPartNameEn'
	}, {
		name: 'parentPartPUpcfna'
	}, {
		name: 'partNameZh'
	}, {
		name: 'partNameEn'
	}, {
		name: 'productUpcfnaNoteZh'
	}, {
		name: 'productUpcfnaNoteEn'
	}, {
		name: 'salesUpcfnaCode'
	}, {
		name: 'salesUpcfnaNoteZh'
	}, {
		name: 'salesUpcfnaNoteEn'
	}, {
		name: 'source'
	}, {
		name: 'plmStructureStatusCode'
	}, {
		name: 'plmStructureStatusName'
	}, {
		name: 'steCode'
	}, {
		name: 'steName'
	}, {
		name: 'servicePolicyCode'
	}, {
		name: 'servicePolicyName'
	}, {
		name: 'serviceSupportTypeCode'
	}, {
		name: 'serviceSupportTypeName'
	}, {
		name: 'serviceSupportTypeNote'
	}, {
		name: 'wasServicePart'
	}, {
		name: 'servicePartTypeCode'
	}, {
		name: 'servicePartTypeName'
	}, {
		name: 'supersessions'
	}, {
		name: 'newPartCode'
	}, {
		name: 'supersessionTypeCode'
	}, {
		name: 'supersessionTypeName'
	}, {
		name: 'treatmentProposalCode'
	}, {
		name: 'treatmentProposalName'
	}, {
		name: 'purchaseDemandCode'
	}, {
		name: 'purchaseStatusCode'
	}, {
		name: 'purchaseDemandName'
	}, {
		name: 'purchaseStatusName'
	}, {
		name: 'salesStatusCode'
	}, {
		name: 'salesStatusName'
	}, {
		name: 'isManualCode'
	}, {
		name: 'isManualName'
	}, {
		name: 'leaf'
	}, {
		name: 'level'
	}, {
		name: 'children'
	}]
});