Ext.define('App.model.partEngineering.AftersalesProductionPartMapping', {
	extend: 'App.model.common.Base',
	fields: [{
		name: 'id'
	}, {
		name: 'afterSalesPartCode'
	}, {
		name: 'afterSalesPartNameZh'
	}, {
		name: 'afterSalesPartNameEn'
	}, {
		name: 'afterSalesPartDescription'
	}, {
		name: 'afterSalesServicePolicyCode'
	}, {
		name: 'afterSalesServicePolicyName'
	}, {
		name: 'afterSalesPurchaseDemandCode'
	}, {
		name: 'afterSalesPurchaseStatusCode'
	}, {
		name: 'afterSalesPurchaseDemandName'
	}, {
		name: 'afterSalesPurchaseStatusName'
	}, {
		name: 'afterSalesSalesStatusCode'
	}, {
		name: 'afterSalesSalesStatusName'
	}, {
		name: 'afterSalesQty'
	}, {
		name: 'referPartCode'
	}, {
		name: 'referPartNameZh'
	}, {
		name: 'referPartNameEn'
	}, {
		name: 'referPartDescription'
	}, {
		name: 'referServicePolicyCode'
	}, {
		name: 'referServicePolicyName'
	}, {
		name: 'referPurchaseDemandCode'
	}, {
		name: 'referPurchaseStatusCode'
	}, {
		name: 'referPurchaseDemandName'
	}, {
		name: 'referPurchaseStatusName'
	}, {
		name: 'referSalesStatusCode'
	}, {
		name: 'referSalesStatusName'
	}, {
		name: 'deletedCode'
	}, {
		name: 'deletedName'
	}, {
		name: 'systemicCreated'
	}]
});