Ext.define('App.model.partEngineering.Electrophoresis', {
	extend: 'App.model.common.Base',
	fields: [{
		name: 'code'
	}, {
		name: 'description'
	}, {
		name: 'elposPrimsColorOption'
	}, {
		name: 'elposPrimsColorOptionName'
	}, {
		name: 'nameEn'
	}, {
		name: 'nameZh'
	}, {
		name: 'note'
	}, {
		name: 'originalPartCode'
	}, {
		name: 'originalPartNameEn'
	}, {
		name: 'originalPartNameZh'
	}, {
		name: 'originalPurchaseDemandCode'
	}, {
		name: 'originalPurchaseDemandName'
	}, {
		name: 'originalPurchaseStatusCode'
	}, {
		name: 'originalPurchaseStatusName'
	}, {
		name: 'originalSalesStatusCode'
	}, {
		name: 'originalSalesStatusName'
	}, {
		name: 'originalServicePolicyCode'
	}, {
		name: 'originalServicePolicyName'
	}, {
		name: 'purchaseDemandCode'
	}, {
		name: 'purchaseDemandName'
	}, {
		name: 'purchaseStatusCode'
	}, {
		name: 'purchaseStatusName'
	}, {
		name: 'salesStatusCode'
	}, {
		name: 'salesStatusName'
	}, {
		name: 'servicePolicyCode'
	}, {
		name: 'servicePolicyName'
	}, {
		name: 'createdBy'
	}, {
		name: 'createdDate',
		convert: function (val) {
			return Ext.util.Format.localDate(val);
		}
	}, {
		name: 'modifiedBy'
	}, {
		name: 'modifiedDate',
		convert: function (val) {
			return Ext.util.Format.localDate(val);
		}
	}]
});