Ext.define('App.model.partEngineering.NewPartTask', {
	extend: 'Ext.data.Model',
	fields: [{
		name: 'afterSaleNote'
	}, {
		name: 'collaborationSpace'
	}, {
		name: 'description'
	}, {
		name: 'designCollaboration'
	}, {
		name: 'designResponsibility'
	}, {
		name: 'designStageName'
	}, {
		name: 'ecoCode'
	}, {
		name: 'ecrCode'
	}, {
		name: 'endDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'initialProject'
	}, {
		name: 'oneLevelPartCodes'
	}, {
		name: 'parentPartCodes'
	}, {
		name: 'partCode'
	}, {
		name: 'partNameEn'
	}, {
		name: 'partNameZh'
	}, {
		name: 'plmColors'
	}, {
		name: 'plmIsColorPart'
	}, {
		name: 'plmIsServicePart'
	}, {
		name: 'plmIsSparePart'
	}, {
		name: 'plmIsColorPartName'
	}, {
		name: 'plmIsServicePartName'
	}, {
		name: 'plmIsSparePartName'
	}, {
		name: 'plmNote'
	}, {
		name: 'plmPartType'
	}, {
		name: 'productUpcfnas'
	}, {
		name: 'recommendServicePolicyCode'
	}, {
		name: 'recommendServicePolicyName'
	}, {
		name: 'recommendSteCode'
	}, {
		name: 'recommendSteName'
	}, {
		name: 'referProductionPartCode'
	}, {
		name: 'sapNote'
	}, {
		name: 'servicePartTypeCode'
	}, {
		name: 'servicePartTypeName'
	}, {
		name: 'servicePolicyCode'
	}, {
		name: 'servicePolicyName'
	}, {
		name: 'serviceSupportTypeCode'
	}, {
		name: 'serviceSupportTypeName'
	}, {
		name: 'serviceSupportTypeNote'
	}, {
		name: 'smtCode'
	}, {
		name: 'smtName'
	}, {
		name: 'source'
	}, {
		name: 'startDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'steCode'
	}, {
		name: 'steModifiedNote'
	}, {
		name: 'steName'
	}, {
		name: 'taskStatusCode'
	}, {
		name: 'taskStatusName'
	}, {
		name: 'treatmentProposalName'
	}, {
		name: 'steModifiedDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}]
});