Ext.define('App.model.partEngineering.Parts', {
	extend: 'App.model.common.Base',
	fields: [{
		name: 'code'
	}, {
		name: 'nameZh'
	}, {
		name: 'nameEn'
	}, {
		name: 'description'
	}, {
		name: 'designStageCode'
	}, {
		name: 'designStageName'
	}, {
		name: 'servicePolicyCode'
	}, {
		name: 'servicePolicyName'
	}, {
		name: 'servicePolicyDetermineDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'serviceSupportTypeCode'
	}, {
		name: 'serviceSupportTypeName'
	}, {
		name: 'serviceSupportTypeNote'
	}, {
		name: 'supersessions'
	}, {
		name: 'newPartCode'
	}, {
		name: 'newPartNameZh'
	}, {
		name: 'newPartNameEn'
	}, {
		name: 'supersessionTypeCode'
	}, {
		name: 'supersessionTypeName'
	}, {
		name: 'treatmentProposalCode'
	}, {
		name: 'treatmentProposalName'
	}, {
		name: 'forecastBreakPointDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'supersessionNote'
	}, {
		name: 'servicePartTypeCode'
	}, {
		name: 'servicePartTypeName'
	}, {
		name: 'steCode'
	}, {
		name: 'steName'
	}, {
		name: 'inheritanceStructureCode'
	}, {
		name: 'inheritanceStructureName'
	}, {
		name: 'partClassifyCode'
	}, {
		name: 'partClassifyName'
	}, {
		name: 'plmNote'
	}, {
		name: 'sapNote'
	}, {
		name: 'afterSaleNote'
	}, {
		name: 'referProductionPartCode'
	}, {
		name: 'plmPartType'
	}, {
		name: 'salesStatusCode'
	}, {
		name: 'salesStatusName'
	}, {
		name: 'stockStatusCode'
	}, {
		name: 'stockStatusName'
	}, {
		name: 'pricingStatusCode'
	}, {
		name: 'pricingStatusName'
	}, {
		name: 'salesStatusSyncDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'stockStatusSyncDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'pricingStatusSyncDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'plmIsColorPartCode'
	}, {
		name: 'plmIsColorPartName'
	}, {
		name: 'colorCode'
	}, {
		name: 'colorName'
	}, {
		name: 'generatePartColorNames'
	}, {
		name: 'strategy'
	}, {
		name: 'initialMakeOrBuy'
	}, {
		name: 'designResponsibility'
	}, {
		name: 'positionNo'
	}, {
		name: 'sorCode'
	}, {
		name: 'plmIsServicePartCode'
	}, {
		name: 'plmIsServicePartName'
	}, {
		name: 'plmIsSparePartCode'
	}, {
		name: 'plmIsSparePartName'
	}, {
		name: 'initialProject'
	}, {
		name: 'designCollaboration'
	}, {
		name: 'collaborationSpace'
	}, {
		name: 'plmOwner'
	}, {
		name: 'isTracePartCode'
	}, {
		name: 'isMaintainPartCode'
	}, {
		name: 'isVulnerablePartCode'
	}, {
		name: 'isAccidentPartCode'
	}, {
		name: 'isTracePartName'
	}, {
		name: 'isMaintainPartName'
	}, {
		name: 'isVulnerablePartName'
	}, {
		name: 'isAccidentPartName'
	}, {
		name: 'damageCycleCode'
	}, {
		name: 'damageCycleName'
	}, {
		name: 'hscode'
	}, {
		name: 'onlineDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'offlineDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'onlineOfflineNote'
	}, {
		name: 'smtCode'
	}, {
		name: 'smtName'
	}, {
		name: 'supplierCode'
	}, {
		name: 'supplierName'
	}, {
		name: 'supplierTele'
	}, {
		name: 'supplierContact'
	}, {
		name: 'supplierPartCode'
	}, {
		name: 'purchaseDemandCode'
	}, {
		name: 'purchaseStatusCode'
	}, {
		name: 'purchaseDemandName'
	}, {
		name: 'purchaseStatusName'
	}, {
		name: 'purchaseDemandDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'purchaseStatusSyncDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'isPurchaseCode'
	}, {
		name: 'isPurchaseName'
	}, {
		name: 'purchaseEngineerCode'
	}, {
		name: 'purchaseEngineerName'
	}, {
		name: 'isSpecialPurchaseCode'
	}, {
		name: 'isSpecialPurchaseName'
	}, {
		name: 'supplierMoq'
	}, {
		name: 'dealerMoq'
	}, {
		name: 'middleWarehouseMoq'
	}, {
		name: 'plmWeight'
	}, {
		name: 'plmUnit'
	}, {
		name: 'sapWeight'
	}, {
		name: 'length'
	}, {
		name: 'width'
	}, {
		name: 'height'
	}, {
		name: 'mpq'
	}, {
		name: 'material'
	}, {
		name: 'standard'
	}, {
		name: 'reserveProposalCode'
	}, {
		name: 'reserveProposalName'
	}, {
		name: 'packageEngineerCode'
	}, {
		name: 'packageEngineerName'
	}, {
		name: 'packageStatusCode'
	}, {
		name: 'packageStatusName'
	}, {
		name: 'packageStatusDate',
		mapping: function(data) {
			return Ext.util.Format.localDate(data[this.name]);
		}
	}, {
		name: 'source'
	}, {
		name: 'recommendServicePolicyCode'
	}, {
		name: 'recommendServicePolicyName'
	}]
});