Ext.define('App.view.partEngineering.aftersalesProductionPartMapping.Grid', {
	extend: 'Ext.ux.component.grid.Grid',
	alias: 'widget.aftersalesproductionpartmappinggrid',
	store: 'App.store.partEngineering.AftersalesProductionPartMapping',
	multiSelectCheckbox: false,
	controlButtons: ['update'],
	tbar: [{
		iconCls: 'x-fa fa-plus-square-o',
		tooltip: '新增',
		text: '新增',
		action: 'create',
		ui: 'grid-toolbar'
	}, {
		iconCls: 'x-fa fa-edit',
		text: '修改',
		tooltip: '修改',
		action: 'update',
		disabled: true,
		singleSelectEnable: true,
		ui: 'grid-toolbar',
		enableCondition: {
			name: 'systemicCreated',
			value: false
		}
	}, {
		xtype: 'button',
		text: '导出',
		action: 'export',
		iconCls: 'iconfont icon-export',
		ui: 'grid-toolbar',
		exportUrl: App.globalConfig.path + '/aftersales-production-rel/export'
	}],
	columns: [{
		text: '售后专用件编码',
		dataIndex: 'afterSalesPartCode',
		width: 140,
		locked: true
	}, {
		text: '售后专用件中文名称',
		dataIndex: 'afterSalesPartNameZh',
		width: 140
	}, {
		text: '售后专用件英文名称',
		dataIndex: 'afterSalesPartNameEn',
		width: 140
	}, {
		text: '售后专用件描述',
		dataIndex: 'afterSalesPartDescription',
		width: 120
	}, {
		text: '售后专用件用量',
		dataIndex: 'afterSalesQty',
		width: 120
	}, {
		text: '维修策略',
		dataIndex: 'afterSalesServicePolicyName',
		width: 120
	}, {
		text: '采购需求',
		dataIndex: 'afterSalesPurchaseDemandName',
		width: 120
	}, {
		text: '采购状态',
		dataIndex: 'afterSalesPurchaseStatusName',
		width: 120
	}, {
		text: '销售状态',
		dataIndex: 'afterSalesSalesStatusName',
		width: 120
	}, {
		text: '生产件编码',
		dataIndex: 'referPartCode',
		width: 120
	}, {
		text: '生产件中文名称',
		dataIndex: 'referPartNameZh',
		width: 120
	}, {
		text: '生产件英文名称',
		dataIndex: 'referPartNameEn',
		width: 120
	}, {
		text: '生产件描述',
		dataIndex: 'referPartDescription',
		width: 120
	}, {
		text: '维修策略',
		dataIndex: 'referServicePolicyName',
		width: 120
	}, {
		text: '采购需求',
		dataIndex: 'referPurchaseDemandName',
		width: 120
	}, {
		text: '采购状态',
		dataIndex: 'referPurchaseStatusName',
		width: 120
	}, {
		text: '销售状态',
		dataIndex: 'referSalesStatusName',
		width: 120
	}, {
		text: '删除标识',
		dataIndex: 'deletedName',
		width: 120
	}, {
		text: '创建人',
		dataIndex: 'createdBy',
		width: 120
	}, {
		text: '创建时间',
		dataIndex: 'createdDate',
		width: 140
	}, {
		text: '修改人',
		dataIndex: 'modifiedBy',
		width: 120
	}, {
		text: '修改时间',
		dataIndex: 'modifiedDate',
		width: 140
	}]
});