Ext.define('App.view.basicInfo.legendInfo.Query', {
    extend: 'Ext.ux.component.filter.Query',
    alias: 'widget.legendinfoquery',
    items: [{
        items: [{
            fieldLabel: '图例编码',
            name: 'code'
        }, {
            fieldLabel: '图例名称',
            name: 'name'
        }, {
            fieldLabel: '图例标准名称编码',
            name: 'legendStandardCode'
        }, {
            fieldLabel: '图例标准名称',
            name: 'legendStandardName'
        }, {
            fieldLabel: '图例文件名',
            name: 'photoOriginalFilename'
        }, {
            fieldLabel: '图例备注',
            name: 'note'
        }, {
            allowBlank: true,
            xtype: 'treecombo',
            fieldLabel: '所属图例分组',
            rootVisible: false,
            name: 'groupCode',
            canSelectFolders: false,
            isAllExpand: true,
            store: Ext.create('App.store.common.LegendGroup')
        }, {
            fieldLabel: '创建人',
            name: 'createdBy'
        }, {
            xtype: 'datefield',
            fieldLabel: '创建时间-起',
            name: 'createdDate_S',
            format: 'Y-m-d'
        }, {
            xtype: 'datefield',
            fieldLabel: '创建时间-止',
            name: 'createdDate_E',
            format: 'Y-m-d'
        }, {
            fieldLabel: '修改人',
            name: 'modifiedBy'
        }, {
            xtype: 'datefield',
            fieldLabel: '修改时间-起',
            name: 'modifiedDate_S',
            format: 'Y-m-d'
        }, {
            xtype: 'datefield',
            fieldLabel: '修改时间-止',
            name: 'modifiedDate_E',
            format: 'Y-m-d'
        }]
    }]
});