Ext.define('App.model.legendCatalog.LegendUsage', {
	extend: 'App.model.common.Base',
	fields: [{
		name: 'brandCode'
	}, {
		name: 'brandName'
	}, {
		name: 'legendCode'
	}, {
		name: 'legendGroupCode'
	}, {
		name: 'legendGroupNoteZh'
	}, {
		name: 'legendNameEn'
	}, {
		name: 'legendNameZh'
	}, {
		name: 'legendNote'
	}, {
		name: 'legendStandardNameCode'
	}, {
		name: 'legendStandardNameNameEn'
	}, {
		name: 'legendStandardNameNameZh'
	}, {
		name: 'oldLegendCode'
	}, {
		name: 'photoOriginalFilename'
	}, {
        name: 'photoUltimatelyFilename'
    }, {
    	name: 'photoThumbnailFilename'
	}, {
		name: 'seriesCode'
	}, {
		name: 'seriesName'
	}]
});