Ext.define('App.view.partEngineering.parts.Grid', {
	extend: 'Ext.ux.component.grid.Grid',
	alias: 'widget.partsgrid',
	store: 'App.store.partEngineering.Parts',
	multiSelectCheckbox: false,
	tbar: [{
		xtype: 'button',
		text: '导出',
		action: 'export',
		iconCls: 'iconfont icon-export',
		ui: 'grid-toolbar',
		exportUrl: App.globalConfig.path + '/part/export'
	}],
	columns: [{
		text: '操作',
		locked: true,
		align: 'center',
		width: 160,
		renderer: function(data, metadata, record) {
			var html = [],
				code = record.get('code'),
				partUrl = App.globalConfig.path + '/part/detail-page/' + code;

			html.push('<a href="' + partUrl + '" data-action="part" target="_blank" class="btn-tb-link-small">Part</a>');
			html.push('<a href="javascript:;" data-action="act"  class="btn-tb-link-small">ACT</a>');

			return html.join('&nbsp;&nbsp;');
		}
	}, {
		text: '配件编码',
		dataIndex: 'code',
		locked: true,
		width: 120
	}, {
		text: '配件中文名称',
		dataIndex: 'nameZh',
		width: 120
	}, {
		text: '配件英文名称',
		dataIndex: 'nameEn',
		width: 120
	}, {
		text: '配件备注(DRE)',
		dataIndex: 'description',
		width: 120
	}, {
		text: '设计阶段',
		dataIndex: 'designStageName',
		width: 120
	}, {
		text: '维修策略',
		dataIndex: 'servicePolicyName',
		width: 120
	}, {
		text: '维修支持类型',
		dataIndex: 'serviceSupportTypeName',
		width: 120
	}, {
		text: '支持类型备注(note)',
		dataIndex: 'serviceSupportTypeNote',
		width: 120
	}, {
		text: '是否标识过维修件',
		dataIndex: 'wasServicePart',
		width: 120
	}, {
		text: '替换类型',
		dataIndex: 'supersessionTypeName',
		width: 120,
		sortable: false
	}, {
		text: '处理建议',
		dataIndex: 'treatmentProposalName',
		width: 120,
		sortable: false
	}, {
		text: '替换后配件编码',
		dataIndex: 'newPartCode',
		width: 120,
		sortable: false
	}, {
		text: '替换后配件中文名称',
		dataIndex: 'newPartNameZh',
		width: 120,
		sortable: false
	}, {
		text: '替换后配件英文名称',
		dataIndex: 'newPartNameEn',
		width: 120,
		sortable: false
	}, {
		text: '预估断点时间',
		dataIndex: 'forecastBreakPointDate',
		width: 140,
		sortable: false
	}, {
		text: '替换备注',
		dataIndex: 'supersessionNote',
		width: 120,
		sortable: false
	}, {
		text: '维修件类型',
		dataIndex: 'servicePartTypeName',
		width: 120
	}, {
		text: '生成颜色',
		dataIndex: 'generatePartColorNames',
		width: 120,
		sortable: false
	}, {
		text: '设计颜色',
		dataIndex: 'plmGeneratedColorNames',
		width: 120,
		sortable: false
	}, {
		text: '颜色',
		dataIndex: 'colorName',
		width: 120
	}, {
		text: '维修策略判定时间',
		dataIndex: 'servicePolicyDetermineDate',
		width: 140
	}, {
		text: 'STE',
		dataIndex: 'steName',
		width: 120
	}, {
		text: '继承结构',
		dataIndex: 'inheritanceStructureName',
		width: 120
	}, {
		text: '采购需求',
		dataIndex: 'purchaseDemandName',
		width: 120
	}, {
		text: '采购状态',
		dataIndex: 'purchaseStatusName',
		width: 120
	}, {
		text: '销售状态',
		dataIndex: 'salesStatusName',
		width: 120
	}, {
		text: '库存状态',
		dataIndex: 'stockStatusName',
		width: 120
	}, {
		text: '定价状态',
		dataIndex: 'pricingStatusName',
		width: 120
	}, {
		text: '包装状态',
		dataIndex: 'packageStatusName',
		width: 120
	}, {
		text: '配件分类名称',
		dataIndex: 'partClassifyName',
		width: 120
	}, {
		text: '配件备注(PLM)',
		dataIndex: 'plmNote',
		width: 120
	}, {
		text: '配件备注(SAP)',
		dataIndex: 'sapNote',
		width: 120
	}, {
		text: '配件备注(STE)',
		dataIndex: 'afterSaleNote',
		width: 120
	}, {
		text: '参考生产件号',
		dataIndex: 'referProductionPartCode',
		width: 120
	}, {
		text: '配件类型(PLM)',
		dataIndex: 'plmPartType',
		width: 120
	}, {
		text: '是否颜色件(PLM)',
		dataIndex: 'plmIsColorPartName',
		width: 120
	}, {
		text: '设计职责',
		dataIndex: 'designResponsibility',
		width: 120
	}, {
		text: '分组号',
		dataIndex: 'positionNo',
		width: 120
	}, {
		text: '初始项目',
		dataIndex: 'initialProject',
		width: 120
	}, {
		text: '所有者(PLM)',
		dataIndex: 'plmOwner',
		width: 120
	}, {
		text: '海关编码',
		dataIndex: 'hscode',
		width: 120
	}, {
		text: '是否追溯件',
		dataIndex: 'isTracePartName',
		width: 120
	}, {
		text: '是否保养件',
		dataIndex: 'isMaintainPartName',
		width: 120
	}, {
		text: '是否易损件',
		dataIndex: 'isVulnerablePartName',
		width: 120
	}, {
		text: '是否事故件',
		dataIndex: 'isAccidentPartName',
		width: 120
	}, {
		text: '损坏周期',
		dataIndex: 'damageCycleName',
		width: 120
	}, {
		text: '上线时间',
		dataIndex: 'onlineDate',
		width: 140
	}, {
		text: '下线时间',
		dataIndex: 'offlineDate',
		width: 140
	}, {
		text: '上下时间备注',
		dataIndex: 'onlineOfflineNote',
		width: 120
	}, {
		text: 'SMT',
		dataIndex: 'smtName',
		width: 120
	}, {
		text: '供应商编码',
		dataIndex: 'supplierCode',
		width: 120
	}, {
		text: '供应商名称',
		dataIndex: 'supplierName',
		width: 120
	}, {
		text: '供应商联系方式',
		dataIndex: 'supplierTele',
		width: 120
	}, {
		text: '供应商联系人',
		dataIndex: 'supplierContact',
		width: 120
	}, {
		text: '采购工程师',
		dataIndex: 'purchaseEngineerName',
		width: 120
	}, {
		text: '配件有效期',
		dataIndex: 'validityPeriod',
		width: 120
	}, {
		text: '供应商最小订购量',
		dataIndex: 'supplierMoq',
		width: 120
	}, {
		text: '中间库最小订购量',
		dataIndex: 'middleWarehouseMoq',
		width: 120
	}, {
		text: '经销商最小订购量',
		dataIndex: 'dealerMoq',
		width: 120
	}, {
		text: '重量(PLM)',
		dataIndex: 'plmWeight',
		width: 120
	}, {
		text: '单位',
		dataIndex: 'plmUnit',
		width: 120
	}, {
		text: '重量(SAP)',
		dataIndex: 'sapWeight',
		width: 120
	}, {
		text: '长',
		dataIndex: 'length',
		width: 120
	}, {
		text: '宽',
		dataIndex: 'width',
		width: 120
	}, {
		text: '高',
		dataIndex: 'height',
		width: 120
	}, {
		text: '最小包装单元',
		dataIndex: 'mpq',
		width: 120
	}, {
		text: '材料',
		dataIndex: 'material',
		width: 120
	}, {
		text: '规格',
		dataIndex: 'standard',
		width: 120
	}, {
		text: '采购需求更新时间',
		dataIndex: 'purchaseDemandDate',
		width: 140
	}, {
		text: '采购状态同步时间',
		dataIndex: 'purchaseStatusSyncDate',
		width: 140
	}, {
		text: '销售状态同步时间',
		dataIndex: 'salesStatusSyncDate',
		width: 140
	}, {
		text: '库存状态同步时间',
		dataIndex: 'stockStatusSyncDate',
		width: 140
	}, {
		text: '定价状态同步时间',
		dataIndex: 'pricingStatusSyncDate',
		width: 140
	}, {
		text: '包装工程师',
		dataIndex: 'packageEngineerName',
		width: 120
	}, {
		text: '包装材料编码',
		dataIndex: 'packageMaterialCode',
		width: 120
	}, {
		text: '包装材料描述',
		dataIndex: 'packageMaterialDescription',
		width: 120
	}, {
		text: '包装材料类型',
		dataIndex: 'packageMaterialType',
		width: 120
	}, {
		text: '包装材料长',
		dataIndex: 'packageMaterialLength',
		width: 120
	}, {
		text: '包装材料宽',
		dataIndex: 'packageMaterialWidth',
		width: 120
	}, {
		text: '包装材料高',
		dataIndex: 'packageMaterialHeight',
		width: 120
	}, {
		text: '是否紧急订单件',
		dataIndex: 'isRushOrderPartName',
		width: 120
	}, {
		text: '创建人',
		dataIndex: 'createdBy',
		width: 120
	}, {
		text: '创建时间',
		dataIndex: 'createdDate',
		width: 140
	}, {
		text: '修改人',
		dataIndex: 'modifiedBy',
		width: 120
	}, {
		text: '修改时间',
		dataIndex: 'modifiedDate',
		width: 140
	}]
});